config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards
  resources :artists do
    resources :songs 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :billboard, through: :songs
  
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  # Associations
  # dependent is only in the parent, deletes child.  
  has_many :artists, dependent: :destroy 
  has_many :songs

  # make sure that data comes in following certain constraints.
  validates :title, :description, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_billboard 
  before_action :set_artists, only: [:show, :edit, :update, :destroy]
  def index
    @artists = @billboard.artists 
  end

  def show
  end

  def new
    @artist = @billboard.artists.new 
    render partial: "form"
  end

  def create 
    @artist = @billboard.artists.new(artist_params)
    if @artist.save
      redirect_to [@billboard, @artist]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @artist.update(artist_params)
      redirect_to [@billboard, @artist]
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to billboard_artists_path
  end

  private 
    def set_billboard
      @billboard = Billboard.find(params[:billboard_id])
    end

    def set_artists
      @topic = Artist.find(params[:id])
    end
    
    def artist_params
      params.require(:artist).permit(:title, :rank)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  def index
    @billboards = Billboard.all 
  end

  def show
    @billboard = Billboard.find(params[:id])
  end

  def new
    @billboard = Billboard.new
    render partial: 'form' # pertains to views, partial is a shared view, reuse over and over again 
  end
  
  def create #place next to new, added
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect billboards_path
    else
      render :new
    end
  end

  def edit #do this before update
    @billboard = Billboard.find(params[:id])
    render partinal: 'form' # pertains to views, partial is a shared view, reuse over and over again (you should find it views)
  end

  def update #added
    @billboard = Billboard.find(params[:id])
    if @billboard.update(billboard_params)
      redirect billboards_path
    else
      render :edit
    end
  end 

  def destroy #added 
    billboard.find(params[:id]).destroy
    redirect billboards_path
  end

  private #added
  def billboard_params
    params.require(:billboard).permit(:title, :description)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  beforce_action :set_artist
  beforce_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs
  end

  def show
  end

  def new
    @billboards = Billboard.all - @artist.billboards 
    @song = @artist.songs.new
  end

  def create
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to artist_songs_path(@artist)
    else
      render :new
    end
  end

  def edit
    @billboards = Billboard.all - @artist.billboards
  end

  def update
    if @songs.update(song_params)
      redirect_to artist_songs_path(@artist)
    else
      render :edit 
    end 
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  def set_song
    @songs = @artist.songs.find(params[:id])
  end 

  private
    def set_artist
      @artist =Artist.find(params[:artist_id])
    end
    
    def song_params
      params.require(:song).permit(:role, :billboard_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.submit%>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<% render 'form' %>

app/views/artists/index.html.erb
<h1>All Artist</h1>%
<%= link_to 'add artist' new_artis_path %>
<hr />
<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.name, artist %>
    </li>
  <% end %>
</ul>  

app/views/artists/new.html.erb
<h1>New Artist</h1>
<% render 'form' %>

app/views/artists/show.html.erb
<h1><%= @Artists.name %></h1>
<hr />
<h2>Billboards</h2>
<ul>
  <% @artist.billboards.each do |billboard| %>
    <li>
      <%= link_to billboard.name, billboard %>
    </li>
  <% end %>
</ul>
<br />
<%= link_to 'Delete Artist', @artist, method: :delete %>

app/views/billboards/_form.html.erb
  <%= form_for @billboard do |f| %>

<%#= form_with(model: @billboard, local: true, class: 'styled form') do |f| %>
  <%= f.label :title %> 
  <%= f.text_field :title, required: true, placeholder: 'billboard title' %>

  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Edit Billboard</h1>
<%= render 'form' %>

app/views/billboards/index.html.erb
<h1>All Billboard</>
<%= link_to 'Add Billboards', new_billboard_path %>
<hr />
<h2><%= @billboards.length <= 0 ? "no billboards" : '' %></h2>
<ul>
  <% @billboards.each do |billboard| %>
    <li>
      <%= link_to billboard.name, billboard %>
    </li>
  <% end %>  
</ul>

app/views/billboards/new.html.erb
<h1>New Billboards</h1>
<%= render 'form' %>

app/views/billboards/show.html.erb
<h1><%= @billboard.title %></h1>
<hr />
<p>What do you want to do?</p>
<%= link_to 'Edit billboard', edit_billboard_path(@billboard) %>
<br />
<%= link_to 'Delete billboard', @billboard, method: :delete  %>
<br />
<%= link_to 'View Artists', billboard_artists_path(@billboard)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>